---
#
# tasks file for ansible-role-disable_crash_reporters
#
# vim:et:ts=2:ft=ansible

- name: Get package facts
  ansible.builtin.package_facts:
    manager: "auto"
  no_log: true

- name: Whoopsie
  when: _disable_crash_reporters.disable_whoopsie and 'whoopsie' in ansible_facts.packages
  block:
    - name: Deactivate Whoopsie daemon sending crash reports
      ansible.builtin.lineinfile:
        dest: /etc/default/whoopsie
        regexp: "^report_crashes"
        line: "report_crashes=false"
        state: present

    - name: Ensure Whoopsie daemon is stopped and disabled
      ansible.builtin.service:
        name: whoopsie
        state: stopped
        enabled: false

- name: Apport
  when: _disable_crash_reporters.disable_apport and 'apport' in ansible_facts.packages
  block:
    - name: Deactivate apport daemon crash report collection
      ansible.builtin.lineinfile:
        dest: /etc/default/apport
        regexp: "^enabled"
        line: "enabled=0"
        state: present

    - name: Ensure apport daemon is stopped and disabled
      ansible.builtin.service:
        name: apport
        state: stopped
        enabled: false
